# Node 20
[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
cmds = ["npm run build"]
# SADECE klasörleri cache'le – tsconfig.tsbuildinfo'yı çıkarıyoruz
cacheDirectories = [".next/cache", "node_modules/.cache"]

[start]
cmd = "npm run start"
